### ISSUE TITLE
Cannot get pyTweetBot to do some action

### ISSUE THREAD

**Issue by metmajer** [nschaetti/pyTweetBot#6]
Hi @nschaetti, first let me congratulate you on this amazing project. I'd really love to use this as a tweet generator for [@getcloudn8tv](https://twitter.com/getcloudn8tv). Unfortunately, I am not really able to get the bot to do something useful. As you can see, @getcloudn8tv is still fresh and thus has only a very limited number of followers and followees.

I would assume that the `execute` option would be the best entrypoint to get the bot started. However, even after waiting for longer than an hour, the list of actions remains empty.
```
# python -m pyTweetBot execute --config /data/config.json --log-level 10 --log-file /data/log
INFO:pyTweetBot:Start thread for action type Tweet...
INFO:pyTweetBot:Start thread for action type Retweet...
INFO:pyTweetBot:Start thread for action type Like...
INFO:pyTweetBot:Start thread for action type Follow...
INFO:pyTweetBot:Start thread for action type Unfollow...
DEBUG:pyTweetBot:_get_exec_action : []
INFO:pyTweetBot:Waiting 5.3 minutes for next run of tweet
DEBUG:pyTweetBot:_get_exec_action : []
INFO:pyTweetBot:Waiting 7.9 minutes for next run of retweet
DEBUG:pyTweetBot:_get_exec_action : []
INFO:pyTweetBot:Waiting 7.9 minutes for next run of like
DEBUG:pyTweetBot:_get_exec_action : []
INFO:pyTweetBot:Waiting 16.4 minutes for next run of follow
DEBUG:pyTweetBot:_get_exec_action : []
INFO:pyTweetBot:Waiting 36.5 minutes for next run of unfollow


DEBUG:pyTweetBot:_get_exec_action : []
INFO:pyTweetBot:Waiting 6.5 minutes for next run of tweet
DEBUG:pyTweetBot:_get_exec_action : []
INFO:pyTweetBot:Waiting 4.4 minutes for next run of like
DEBUG:pyTweetBot:_get_exec_action : []
INFO:pyTweetBot:Waiting 4.1 minutes for next run of retweet

DEBUG:pyTweetBot:_get_exec_action : []
INFO:pyTweetBot:Waiting 6.2 minutes for next run of tweet
DEBUG:pyTweetBot:_get_exec_action : []
INFO:pyTweetBot:Waiting 4.2 minutes for next run of retweet
DEBUG:pyTweetBot:_get_exec_action : []
INFO:pyTweetBot:Waiting 6.8 minutes for next run of like


DEBUG:pyTweetBot:_get_exec_action : []
INFO:pyTweetBot:Waiting 5.8 minutes for next run of retweet

DEBUG:pyTweetBot:_get_exec_action : []
INFO:pyTweetBot:Waiting 39.0 minutes for next run of follow
DEBUG:pyTweetBot:_get_exec_action : []
INFO:pyTweetBot:Waiting 9.1 minutes for next run of tweet
DEBUG:pyTweetBot:_get_exec_action : []
INFO:pyTweetBot:Waiting 5.4 minutes for next run of like
```

Now, I don't get a lot of information from the log output. I would really like to see if the bot's keyword search via Google News or for relevant Tweets does get at least some results or not. While the bot was running, a Twitter user that the bot follows ([@metmajer](https://twitter.com/metmajer)) has retweeted [this tweet](https://twitter.com/MayaKaczorowski/status/1009111190998519815), which contains a keyword that is contained in the config's `retweet.keywords` (Kubernetes).

So, my next approach was to use the `find-tweets` command to see whether that gives more insights, but then again this requires me to define a `MODEL` and I cannot see where this is created.

```
# python -m pyTweetBot find-tweets
usage: pyTweetBot find-tweets [-h] --config CONFIG [--log-level LOG_LEVEL]
                              [--log-file LOG_FILE] --model MODEL
                              [--threshold THRESHOLD] [--n-pages N_PAGES]
                              [--text-size TEXT_SIZE]
```

Unfortunately, the documentation on model training doesn't explain this important step. @nschaetti, @tlwt, any additional help would be most valuable. Cheers!

**Comment by nschaetti** [comment]
Hi Martin!

Before posting tweets/retweets or follow new user you need to find new tweets with the tweets command :

For example :
> python -m pyTweetBot find-tweets --config /etc/bots/bot.conf --model /etc/bots/models/find_tweets.p

The model argument is a trained model that will classify which content to tweet or not. You need first to create a dataset of examples :

> python -m pyTweetBot train --dataset test.p --config config.json --text-size 100 --action dataset --source news

It will show you example and ask you if you it is a positive (tweet) or negative (don't tweet) examples. It is quiet long as machine learning algorithms need a lot of examples to work properly. You can then train a model (decision tree, SVM, etc) :

> python -m pyTweetBot train --dataset test.p --config config.json --model mymodel.p --action train --text-size 100 --classifier SVM

You can then use this model for the find-tweet command.

Sorry for the plainful process to make to bot ready to work, I hope to get more time soon to work on that.

Regards,

Nils

**Comment by metmajer** [comment]
Hi Nils!

Thank you so much for the quick update. I should be able to take it from here. Allow me to test this before I close the issue.

Cheers, Martin

**Comment by metmajer** [comment]
@nschaetti, seems like I hit some bugs?

#### python -m pyTweetBot train [...] --source friends

```
# python -m pyTweetBot train --dataset /data/model.p --config /data/config.json --text-size 100 --action dataset --source friends
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/getcloudn8tv-tweet-bot/pyTweetBot/__main__.py", line 361, in <module>
    follower_dataset(twitter_connector, args.dataset, args.info, u"following")
  File "pyTweetBot/follower_dataset.py", line 81, in follower_dataset
    print(pystr.DIALOG_CLASS_LABEL)
AttributeError: 'module' object has no attribute 'DIALOG_CLASS_LABEL'
```

#### python -m pyTweetBot train [...] --source news

```
# python -m pyTweetBot train --dataset /data/model.p --config /data/config.json --text-size 100 --action dataset --source news
INFO:pyTweetBot:Changing hunter to GoogleNewsHunter(search_term=ansible, lang, country, hashtags, languages, n_pages)
INFO:pyTweetBot:Retrieving https://www.google.ch/search?hl=en&gl=us&q=ansible&tbm=nws&start=0
ERROR:pyTweetBot:Error with URL value while retrieving /search?hl=en : unknown url type: /search?hl=en
```
#### python -m pyTweetBot train [...]--source tweets

```
# python -m pyTweetBot train --dataset /data/model.p --config /data/config.json --text-size 100 --action dataset --source tweets
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/getcloudn8tv-tweet-bot/pyTweetBot/__main__.py", line 359, in <module>
    retweet_dataset(config, args.dataset, args.search, args.info, args.source)
  File "pyTweetBot/retweet_dataset.py", line 80, in retweet_dataset
    for keyword in config.get_retweet_config()['keywords']:
AttributeError: 'BotConfig' object has no attribute 'get_retweet_config'
```

Would you suggest I open issues for each of these?

Cheers, Martin

**Comment by nschaetti** [comment]
Hi,

I updated the code for the last issue with 'get_retweet_config'. For the first two, did you try with the last version of the code on the develop branch? Because I don't have these issues on my side. I created a release with the last version of the develop branch for you to try.

Regards,

Nils

**Comment by metmajer** [comment]
Hi @nschaetti, updating the codebase helped, but I've also discovered some more errors (nothing too hard, they could be fixed with considerable efforts). Please see the associated pull requests :) Thanks for your help, closing for now!

**Comment by paulmsw** [comment]
I'm a R guy myself.. but this is one of those projects which has forced me out of my comfort zone.. So I'm going to try to integrate DeepMoji's 2304-dimensional emotional feature vectors - wish me luck.. :)
